env:
  global:
    - PANTS_CONFIG_FILES="pants.travis-ci.ini"
    - ANDROID_SDK_INSTALL_LOCATION="${HOME}/opt/android-sdk-install"
    - ANDROID_HOME="$ANDROID_SDK_INSTALL_LOCATION/android-sdk-linux"

before_cache:
  # Ensure permissions to do the below removals, which happen with or without caching enabled.
  - sudo chown -R travis:travis "${HOME}" "${TRAVIS_BUILD_DIR}"
  # Kill all python bytecode in our cached venvs.  Some files appear to
  # get bytecode compiled in non-yet-understood circumstances leading to
  # a full cache re-pack due to new bytecode files.
  - find build-support -name "*.py[co]" -delete
  # The `ivydata-*.properties` & root level `*.{properties,xml}` files'
  # effect on resolution time is in the noise, but they are
  # re-timestamped in internal comments and fields on each run and this
  # leads to travis-ci cache thrash.  Kill these files before the cache
  # check to avoid un-needed cache re-packing and re-upload (a ~100s
  # operation).
  - find ${HOME}/.ivy2/pants -type f -name "ivydata-*.properties" -delete
  - rm -f ${HOME}/.ivy2/pants/*.{css,properties,xml,xsl}
  # We have several tests that do local file:// url resolves for
  # com.example artifacts, these disrupt the cache but are fast since
  # they're resolved from local files when omitted from the cache.
  - rm -rf ${HOME}/.ivy2/pants/com.example
  # The stats cache contains timestamped reports unused by CI but that
  # thrash the cache.  Skip caching these.
  - rm -rf ${HOME}/.cache/pants/stats

cache:
  directories:
    - ${HOME}/.cache/pants
    - ${HOME}/.ivy2/pants
    # TODO(John Sirois): Update this to ~/.npm/pants when pants starts
    # using its own isolated cache:
    #   https://github.com/pantsbuild/pants/issues/2485
    - ${HOME}/.npm
    - ${HOME}/.android
    - ${ANDROID_SDK_INSTALL_LOCATION}
    - build-support/isort.venv
    - build-support/pants_dev_deps.venv

# NB: There is much repetition in include elements, but there is no known current way to factor
# this duplication up.
matrix:
  include:
    - os: osx
      language: generic
      env:
        - SHARD="OSX Native Engine Binary Builder"
        - NATIVE_ENGINE_DEPLOY=1
      script:
        - ./build-support/bin/native/prepare-binary-deploy.sh

    - os: linux
      dist: trusty
      sudo: required
      # Docker runs will write files as root, so avoid caching for this shard.
      cache: false
      services:
        - docker
      language: python
      python: "2.7.13"
      env:
        - SHARD="Linux Native Engine Binary Builder"
        - NATIVE_ENGINE_DEPLOY=1
        # Use the standard python-2.7 docker Debian Wheezy image for binary compatibility with old
        # linux distros.
        - DOCKER_IMAGE="python:2.7.13-jessie"
      before_install:
        # Remove any Ubuntu binary cruft before building.
        - git clean -fdx
        - rm -rf ~/.cache/pants
        - docker pull $DOCKER_IMAGE
      script:
        # Map virtual mount paths 1:1 to simulate running in-place in travis.
        - docker run --rm -t
          -v "${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}"
          -v "${HOME}:${HOME}"
          -e "HOME=${HOME}"
          "${DOCKER_IMAGE}"
          sh -c "
            cd $TRAVIS_BUILD_DIR && ./build-support/bin/native/prepare-binary-deploy.sh
          "

    # Rust tests
    - os: linux
      dist: trusty
      language: python
      python: "2.7.13"
      env:
        - SHARD="Rust tests"
      script:
        - ./build-support/bin/ci.sh -abcfjklmnprstx

deploy:
  # See: https://docs.travis-ci.com/user/deployment/s3/
  provider: s3
  access_key_id: AKIAIQHTQI5E42SQBSNA
  secret_access_key:
    secure: RQVzsNfZL8AgsXdjZ67j2tWs5Tjl/FKpmE1fyVgldMbua/xhW8dzdFrtOeWjTPX4/+sJZ4U7/tZectBtWejmrXUJiZQKJwJBnsyYxysENTWOV80BEYyoz2RPr8HSVbMZ1ZHtUafzO3OqV1x+Pvgpg8FUeUfsy3TGUk0JREO90Q0=
  bucket: binaries.pantsbuild.org
  local_dir: build-support/bin/native/s3-upload
  # Otherwise travis will stash build-support/bin/native/s3-upload and the deploy will fail.
  skip_cleanup: true
  acl: public_read
  on:
    condition: $NATIVE_ENGINE_DEPLOY = 1
    branch: master
    repo: pantsbuild/pants

# We accept the default travis-ci email author+committer notification
# for now which is enabled even with no `notifications` config.
# notifications:
#   email: ...
