[package]
version = "0.0.1"
name = "process_executor"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]

[dependencies]
bazel_protos = { path = "bazel_protos" }
digest = "0.6.2"
grpcio = { git = "https://github.com/illicitonion/grpc-rs", rev = "8a563f97a15faecb3fe82aeaff24bc64ce187a6f" }
protobuf = "1.4.1"
sha2 = "0.6.0"
